/*++
	Copyright (c) Microsoft Corporation. All Rights Reserved.
	Copyright (c) Bingxing Wang. All Rights Reserved.
	Copyright (c) LumiaWoA authors. All Rights Reserved.

	Module Name:

		device.c

	Abstract:

		Code for handling WDF device-specific requests

	Environment:

		Kernel mode

	Revision History:

--*/

#include <internal.h>
#include <controller.h>
#include <device.h>
#include <spb.h>
//#include <STFingerTipSTouchDriverETW.h>
#include <idle.h>
#include <hid.h>
#include <gpio.h>
#include <device.h>
#include <fts521/fts521internal.h>
#include <report.h>
#include <touch_power/touch_power.h>
#include <device.tmh>

#ifdef ALLOC_PRAGMA
#pragma alloc_text(PAGE, OnD0Exit)
#endif

static
PCSTR
TchRuntimeStateName(
	IN TOUCH_RUNTIME_STATE State
)
{
	switch (State)
	{
	case TouchRuntimeUninitialized:
		return "UNINITIALIZED";
	case TouchRuntimePrepared:
		return "PREPARED";
	case TouchRuntimeStarted:
		return "STARTED";
	case TouchRuntimeD0Active:
		return "D0_ACTIVE";
	case TouchRuntimeDisplayOff:
		return "DISPLAY_OFF";
	case TouchRuntimeResetting:
		return "RESETTING";
	case TouchRuntimeD3:
		return "D3";
	case TouchRuntimeFailed:
		return "FAILED";
	default:
		return "UNKNOWN";
	}
}

static
PCSTR
TchInterruptStateName(
	IN TOUCH_INTERRUPT_STATE State
)
{
	switch (State)
	{
	case TouchInterruptNotCreated:
		return "NOT_CREATED";
	case TouchInterruptCreated:
		return "CREATED";
	case TouchInterruptWdfEnabled:
		return "WDF_ENABLED";
	case TouchInterruptWdfDisabled:
		return "WDF_DISABLED";
	default:
		return "UNKNOWN";
	}
}

static
VOID
TchSetRuntimeState(
	IN PDEVICE_EXTENSION DevContext,
	IN TOUCH_RUNTIME_STATE NewState,
	IN PCSTR Source
)
{
	TOUCH_RUNTIME_STATE oldState;

	oldState = DevContext->RuntimeState;
	DevContext->RuntimeState = NewState;

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_POWER,
		"%s runtime state %s -> %s",
		Source,
		TchRuntimeStateName(oldState),
		TchRuntimeStateName(NewState));
}

static
VOID
TchSetInterruptState(
	IN PDEVICE_EXTENSION DevContext,
	IN TOUCH_INTERRUPT_STATE NewState,
	IN PCSTR Source
)
{
	TOUCH_INTERRUPT_STATE oldState;

	oldState = DevContext->InterruptState;
	DevContext->InterruptState = NewState;

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_POWER,
		"%s interrupt state %s -> %s",
		Source,
		TchInterruptStateName(oldState),
		TchInterruptStateName(NewState));
}

BOOLEAN
OnInterruptIsr(
	IN WDFINTERRUPT Interrupt,
	IN ULONG MessageID
)
/*++

  Routine Description:

	This routine responds to interrupts generated by the
	controller. If one is recognized, it queues a DPC for
	processing.

	This is a PASSIVE_LEVEL ISR. ACPI should specify
	level-triggered interrupts when using FingerTipS 521.

  Arguments:

	Interrupt - a handle to a framework interrupt object
	MessageID - message number identifying the device's
		hardware interrupt message (if using MSI)

  Return Value:

	TRUE if interrupt recognized.

--*/
{
	PDEVICE_EXTENSION devContext;
	NTSTATUS status;

	UNREFERENCED_PARAMETER(MessageID);

	Trace(
		TRACE_LEVEL_ERROR,
		TRACE_REPORTING,
		"OnInterruptIsr - Entry");

	status = STATUS_SUCCESS;
	devContext = GetDeviceContext(WdfInterruptGetDevice(Interrupt));
	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_INTERRUPT,
		"OnInterruptIsr state runtime=%s interrupt=%s reset=%d",
		TchRuntimeStateName(devContext->RuntimeState),
		TchInterruptStateName(devContext->InterruptState),
		devContext->ResetState);

	//
	// For performance tracing, write an ETW event marker
	//
	//EventWriteTouchIsr(&TouchMiniDriverControlGuid);

	//
	// If we're in diagnostic mode, let the diagnostic application handle
	// interrupt servicing
	//
	if (devContext->DiagnosticMode != FALSE)
	{
		goto exit;
	}

	//
	// Service touch interrupts.
	//
	status = Fts521ServiceInterrupts(
		devContext->TouchContext,
		&devContext->I2CContext,
		&devContext->ReportContext);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_REPORTING,
			"Error servicing interrupts - 0x%08lX",
			status);
		goto exit;
	}

exit:

	Trace(
		TRACE_LEVEL_ERROR,
		TRACE_REPORTING,
		"OnInterruptIsr - Exit");
	return TRUE;
}

NTSTATUS
OnInterruptEnable(
	IN WDFINTERRUPT Interrupt,
	IN WDFDEVICE AssociatedDevice
)
{
	PDEVICE_EXTENSION devContext;

	UNREFERENCED_PARAMETER(Interrupt);

	devContext = GetDeviceContext(AssociatedDevice);
	TchSetInterruptState(devContext, TouchInterruptWdfEnabled, "OnInterruptEnable");

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_INTERRUPT,
		"OnInterruptEnable - WDF connected and enabled the interrupt");

	return STATUS_SUCCESS;
}

NTSTATUS
OnInterruptDisable(
	IN WDFINTERRUPT Interrupt,
	IN WDFDEVICE AssociatedDevice
)
{
	PDEVICE_EXTENSION devContext;

	UNREFERENCED_PARAMETER(Interrupt);

	devContext = GetDeviceContext(AssociatedDevice);
	TchSetInterruptState(devContext, TouchInterruptWdfDisabled, "OnInterruptDisable");

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_INTERRUPT,
		"OnInterruptDisable - WDF is disabling or disconnecting the interrupt");

	return STATUS_SUCCESS;
}

NTSTATUS
OnD0Entry(
	IN WDFDEVICE Device,
	IN WDF_POWER_DEVICE_STATE PreviousState
)
/*++

Routine Description:

	This routine will power on the hardware

Arguments:

	Device - WDF device to power on
	PreviousState - Prior power state

Return Value:

	NTSTATUS indicating success or failure

*/
{
	NTSTATUS status;
	PDEVICE_EXTENSION devContext;

	devContext = GetDeviceContext(Device);

	UNREFERENCED_PARAMETER(PreviousState);

	status = TchWakeDevice(devContext->TouchContext, &devContext->I2CContext);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_POWER,
			"Error setting device to D0 - 0x%08lX",
			status);
		TchSetRuntimeState(devContext, TouchRuntimeFailed, "OnD0Entry");
		goto exit;
	}

	status = TchRestoreConsoleDisplayState(devContext, "OnD0Entry");
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_POWER,
			"Error restoring display state in D0 - 0x%08lX",
			status);
		TchSetRuntimeState(devContext, TouchRuntimeFailed, "OnD0Entry");
		goto exit;
	}

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_POWER,
		"OnD0Entry leaving interrupt lifecycle to KMDF, state=%s",
		TchInterruptStateName(devContext->InterruptState));


	//
	// KMDF owns interrupt connect/disconnect. Service the chip in case an
	// interrupt asserted before a HID read request was queued.
	//
	devContext->ServiceInterruptsAfterD0Entry = TRUE;

	//
	// Complete any pending Idle IRPs
	//
	TchCompleteIdleIrp(devContext);

exit:
	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_POWER,
		"OnD0Entry - Exit - 0x%08lX",
		status);

	return status;
}

NTSTATUS
OnD0Exit(
	IN WDFDEVICE Device,
	IN WDF_POWER_DEVICE_STATE TargetState
)
/*++

Routine Description:

	This routine will power down the hardware

Arguments:

	Device - WDF device to power off

	PreviousState - Prior power state

Return Value:

	NTSTATUS indicating success or failure

*/
{
	NTSTATUS status;
	PDEVICE_EXTENSION devContext;

	PAGED_CODE();

	devContext = GetDeviceContext(Device);

	UNREFERENCED_PARAMETER(TargetState);

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_POWER,
		"OnD0Exit leaving interrupt lifecycle to KMDF, state=%s",
		TchInterruptStateName(devContext->InterruptState));

	status = TchStopDisplayStateHardwareWork(devContext, "OnD0Exit");
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_POWER,
			"Error stopping display hardware work during D0 exit - 0x%08lX",
			status);
		TchSetRuntimeState(devContext, TouchRuntimeFailed, "OnD0Exit");
		return status;
	}

	TchFlushDisplayStateWorker(devContext, "OnD0Exit");

	status = TchDisableDisplayStateHardwareWork(devContext, "OnD0Exit");
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_POWER,
			"Error disabling display hardware work during D0 exit - 0x%08lX",
			status);
		TchSetRuntimeState(devContext, TouchRuntimeFailed, "OnD0Exit");
		return status;
	}

	status = TchStandbyDevice(devContext->TouchContext, &devContext->I2CContext, &devContext->ReportContext);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_POWER,
			"Error exiting D0 - 0x%08lX", 
			status);
		TchSetRuntimeState(devContext, TouchRuntimeFailed, "OnD0Exit");
	}
	else
	{
		TchSetRuntimeState(devContext, TouchRuntimeD3, "OnD0Exit");
	}

	return status;
}

NTSTATUS
GetGPIO(
	WDFIOTARGET gpio, 
	char* value
)
{
	NTSTATUS status = STATUS_SUCCESS;
	WDF_MEMORY_DESCRIPTOR outputDescriptor;
	WDF_REQUEST_SEND_OPTIONS requestOptions;

	WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&outputDescriptor, value, 1);
	WDF_REQUEST_SEND_OPTIONS_INIT(&requestOptions, WDF_REQUEST_SEND_OPTION_TIMEOUT);
	WDF_REQUEST_SEND_OPTIONS_SET_TIMEOUT(&requestOptions, TOUCH_REL_TIMEOUT_MS(TOUCH_GPIO_TRANSFER_TIMEOUT_MS));

	status = WdfIoTargetSendIoctlSynchronously(gpio, NULL, IOCTL_GPIO_READ_PINS, NULL, &outputDescriptor, &requestOptions, NULL);

	return status;
}

NTSTATUS
SetGPIO(
	WDFIOTARGET gpio, 
	unsigned char* value
)
{
	NTSTATUS status = STATUS_SUCCESS;
	WDF_MEMORY_DESCRIPTOR inputDescriptor, outputDescriptor;
	WDF_REQUEST_SEND_OPTIONS requestOptions;

	WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&inputDescriptor, value, 1);
	WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&outputDescriptor, value, 1);
	WDF_REQUEST_SEND_OPTIONS_INIT(&requestOptions, WDF_REQUEST_SEND_OPTION_TIMEOUT);
	WDF_REQUEST_SEND_OPTIONS_SET_TIMEOUT(&requestOptions, TOUCH_REL_TIMEOUT_MS(TOUCH_GPIO_TRANSFER_TIMEOUT_MS));

	status = WdfIoTargetSendIoctlSynchronously(gpio, NULL, IOCTL_GPIO_WRITE_PINS, &inputDescriptor, &outputDescriptor, &requestOptions, NULL);

	return status;
}

NTSTATUS 
OpenIOTarget(
	PDEVICE_EXTENSION ctx, 
	LARGE_INTEGER res, 
	ACCESS_MASK use, 
	WDFIOTARGET* target
)
{
	NTSTATUS status = STATUS_SUCCESS;
	WDF_OBJECT_ATTRIBUTES ObjectAttributes;
	WDF_IO_TARGET_OPEN_PARAMS OpenParams;
	UNICODE_STRING ReadString;
	WCHAR ReadStringBuffer[260];

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "OpenIOTarget Entry");

	RtlInitEmptyUnicodeString(&ReadString,
		ReadStringBuffer,
		sizeof(ReadStringBuffer));

	status = RESOURCE_HUB_CREATE_PATH_FROM_ID(&ReadString,
		res.LowPart,
		res.HighPart);
	if (!NT_SUCCESS(status)) {
		Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "RESOURCE_HUB_CREATE_PATH_FROM_ID failed 0x%x", status);
		goto Exit;
	}

	WDF_OBJECT_ATTRIBUTES_INIT(&ObjectAttributes);
	ObjectAttributes.ParentObject = ctx->FxDevice;

	status = WdfIoTargetCreate(ctx->FxDevice, &ObjectAttributes, target);
	if (!NT_SUCCESS(status)) {
		Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "WdfIoTargetCreate failed 0x%x", status);
		goto Exit;
	}

	WDF_IO_TARGET_OPEN_PARAMS_INIT_OPEN_BY_NAME(&OpenParams, &ReadString, use);
	status = WdfIoTargetOpen(*target, &OpenParams);
	if (!NT_SUCCESS(status)) {
		Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "WdfIoTargetOpen failed 0x%x", status);
		goto Exit;
	}

Exit:
	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "OpenIOTarget Exit");
	return status;
}

NTSTATUS
SetResetGPIO(
	WDFIOTARGET gpio
)
{
/*++
  Routine Description:

	This routine is separated from the part of setting the GPIO in OnPrepareHardware, 
	so as to configure the GPIO of the stfts521 chip or perform a system reset when desired.

--*/
	NTSTATUS status = STATUS_SUCCESS;
	LARGE_INTEGER delay;

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Starting bring up sequence for the controller");

	status = SetResetGPIOLow(gpio);
	if (!NT_SUCCESS(status))
	{
		goto exit;
	}

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Waiting...");

	delay.QuadPart = -10 * TOUCH_POWER_RAIL_STABLE_TIME;
	KeDelayExecutionThread(KernelMode, TRUE, &delay);

	status = SetResetGPIOHigh(gpio);
	if (!NT_SUCCESS(status))
	{
		goto exit;
	}

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Waiting...");

	delay.QuadPart = -10 * TOUCH_DELAY_TO_COMMUNICATE;
	KeDelayExecutionThread(KernelMode, TRUE, &delay);

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Done");

exit:
	return status;
}

NTSTATUS
SetResetGPIOLow(
	WDFIOTARGET gpio
)
{
	NTSTATUS status;
	unsigned char value;

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Setting reset gpio pin to low");

	value = 0;
	status = SetGPIO(gpio, &value);
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_DRIVER,
			"SetResetGPIOLow failed - 0x%08lX",
			status);
	}

	return status;
}

NTSTATUS
SetResetGPIOHigh(
	WDFIOTARGET gpio
)
{
	NTSTATUS status;
	unsigned char value;

	Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Setting reset gpio pin to high");

	value = 1;
	status = SetGPIO(gpio, &value);
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_DRIVER,
			"SetResetGPIOHigh failed - 0x%08lX",
			status);
	}

	return status;
}

NTSTATUS
OnPrepareHardware(
	IN WDFDEVICE FxDevice,
	IN WDFCMRESLIST FxResourcesRaw,
	IN WDFCMRESLIST FxResourcesTranslated
)
/*++

  Routine Description:

	This routine is called by the PnP manager and supplies thie device instance
	with it's SPB resources (CmResourceTypeConnection) needed to find the I2C
	driver.

  Arguments:

	FxDevice - a handle to the framework device object
	FxResourcesRaw - list of translated hardware resources that
		the PnP manager has assigned to the device
	FxResourcesTranslated - list of raw hardware resources that
		the PnP manager has assigned to the device

  Return Value:

	NTSTATUS indicating sucess or failure

--*/
{
	NTSTATUS status;
	PCM_PARTIAL_RESOURCE_DESCRIPTOR res;
	PDEVICE_EXTENSION devContext;
	FTS521_CONTROLLER_CONTEXT* controllerContext;
	ULONG resourceCount;
	ULONG i;
	BOOLEAN spbInitialized;
	BOOLEAN powerInitialized;
	BOOLEAN contextAllocated;
	BOOLEAN deviceStarted;

	UNREFERENCED_PARAMETER(FxResourcesRaw);

	//EventRegisterMicrosoft_WindowsPhone_TouchMiniDriver();

	status = STATUS_INSUFFICIENT_RESOURCES;
	devContext = GetDeviceContext(FxDevice);
	controllerContext = NULL;
	spbInitialized = FALSE;
	powerInitialized = FALSE;
	contextAllocated = FALSE;
	deviceStarted = FALSE;
	devContext->PoFxPowerSettingCallbackHandle1 = NULL;
	devContext->PoFxPowerSettingCallbackHandle2 = NULL;
	devContext->ResetState = TouchResetIdle;
	devContext->LastDisplayState = TOUCH_DISPLAY_STATE_UNKNOWN;
	RtlZeroMemory(devContext->DisplayStateQueue, sizeof(devContext->DisplayStateQueue));
	devContext->DisplayStateQueueHead = 0;
	devContext->DisplayStateQueueCount = 0;
	devContext->DisplayStateWorkQueued = FALSE;
	devContext->DisplayStateHardwareReady = FALSE;
	devContext->DisplayStateAcceptingWork = FALSE;

	//
	// Get the resouce hub connection ID for our I2C driver
	//
	resourceCount = WdfCmResourceListGetCount(FxResourcesTranslated);

	for (i = 0; i < resourceCount; i++)
	{
		res = WdfCmResourceListGetDescriptor(FxResourcesTranslated, i);

		if (res->Type == CmResourceTypeConnection &&
			res->u.Connection.Class == CM_RESOURCE_CONNECTION_CLASS_SERIAL &&
			res->u.Connection.Type == CM_RESOURCE_CONNECTION_TYPE_SERIAL_I2C)
		{
			devContext->I2CContext.I2cResHubId.LowPart =
				res->u.Connection.IdLowPart;
			devContext->I2CContext.I2cResHubId.HighPart =
				res->u.Connection.IdHighPart;

			status = STATUS_SUCCESS;
		}

		if (res->Type == CmResourceTypeConnection &&
			res->u.Connection.Class == CM_RESOURCE_CONNECTION_CLASS_GPIO &&
			res->u.Connection.Type == CM_RESOURCE_CONNECTION_TYPE_GPIO_IO)
		{
			devContext->ResetGpioId.LowPart =
				res->u.Connection.IdLowPart;
			devContext->ResetGpioId.HighPart =
				res->u.Connection.IdHighPart;

			Trace(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Reset GPIO: %08x-%08x", res->u.Connection.IdHighPart, res->u.Connection.IdLowPart);

			devContext->HasResetGpio = TRUE;
		}
	}

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error finding CmResourceTypeConnection resource - 0x%08lX",
			status);

		goto exit;
	}

	if (devContext->HasResetGpio)
	{
		status = OpenIOTarget(devContext, devContext->ResetGpioId, GENERIC_READ | GENERIC_WRITE, &devContext->ResetGpio);
		if (!NT_SUCCESS(status)) {
			Trace(TRACE_LEVEL_ERROR, TRACE_DRIVER, "OpenIOTarget failed for Reset GPIO 0x%x", status);
			goto exit;
		}
	}

	//
	// Initialize Spb so the driver can issue reads/writes
	//
	status = SpbTargetInitialize(FxDevice, &devContext->I2CContext);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error in Spb initialization - 0x%08lX", 
			status);

		goto exit;
	}
	spbInitialized = TRUE;

	//
	// Initialize Touch Power so the driver can issue power state changes
	//
	status = PowerInitialize(FxDevice);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error in touch power initialization - 0x%08lX",
			status);

		goto exit;
	}
	powerInitialized = TRUE;

	TchSetRuntimeState(devContext, TouchRuntimePrepared, "OnPrepareHardware");

	//
	// Get screen properties and populate context
	//
	TchGetScreenProperties(&devContext->ReportContext.Props);

	//
	// Prepare the hardware for touch scanning
	//
	status = TchAllocateContext(&devContext->TouchContext, FxDevice);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error allocating touch context - 0x%08lX", 
			status);

		goto exit;
	}
	contextAllocated = TRUE;

	//
	// Fetch controller settings from registry
	//
	status = TchRegistryGetControllerSettings(
		devContext->TouchContext,
		devContext->FxDevice);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error retrieving controller settings from registry - 0x%08lX",
			status);

		goto exit;
	}

	//
	// Configure the timer for continuous simulation on synaptics hardware that doesn't support it
	//
	status = ReportConfigureContinuousSimulationTimer(devContext->FxDevice);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error configuring continuous timer - 0x%08lX",
			status);

		goto exit;
	}

	//
	// Start the controller
	//
	status = TchStartDevice(devContext->TouchContext, &devContext->I2CContext);

	Trace(
		TRACE_LEVEL_ERROR,
		TRACE_REPORTING,
		"Touch device - Start");

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error starting touch device - 0x%08lX",
			status);

		goto exit;
	}
	deviceStarted = TRUE;

	TchSetRuntimeState(devContext, TouchRuntimeStarted, "OnPrepareHardware");
	controllerContext = (FTS521_CONTROLLER_CONTEXT*)devContext->TouchContext;

	if (controllerContext->TouchSettings.ChargerDetectionSupported != 0)
	{
		status = STATUS_NOT_SUPPORTED;
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"ChargerDetectionSupported is enabled but FTS521 charger state control is not implemented - 0x%08lX",
			status);
		goto exit;
	}
	else
	{
		devContext->PoFxPowerSettingCallbackHandle1 = NULL;
		Trace(
			TRACE_LEVEL_INFORMATION,
			TRACE_INIT,
			"Skipping AC/DC power callback because charger detection is not supported");
	}

	status = PoRegisterPowerSettingCallback(
		NULL,
		&GUID_CONSOLE_DISPLAY_STATE,
		TchPowerSettingCallback,
		devContext,
		&devContext->PoFxPowerSettingCallbackHandle2
	);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error registering power setting callback (2) - 0x%08lX",
			status);

		goto exit;
	}

	//
	// Set it to FALSE after initialization to avoid a conflict 
	// between the "TchReadReport" method and the "SetResetGPIO" operation.
	//
	devContext->ReportDone = FALSE;

exit:
	if (!NT_SUCCESS(status))
	{
		NTSTATUS cleanupStatus;

		cleanupStatus = TchStopDisplayStateHardwareWork(
			devContext,
			"OnPrepareHardwareCleanup");
		if (!NT_SUCCESS(cleanupStatus))
		{
			Trace(
				TRACE_LEVEL_ERROR,
				TRACE_INIT,
				"Cleanup failed stopping display hardware work - 0x%08lX",
				cleanupStatus);
		}

		if (devContext->PoFxPowerSettingCallbackHandle2 != NULL)
		{
			cleanupStatus = PoUnregisterPowerSettingCallback(
				devContext->PoFxPowerSettingCallbackHandle2);
			if (!NT_SUCCESS(cleanupStatus))
			{
				Trace(
					TRACE_LEVEL_ERROR,
					TRACE_INIT,
					"Cleanup failed unregistering display callback - 0x%08lX",
					cleanupStatus);
			}
			devContext->PoFxPowerSettingCallbackHandle2 = NULL;
		}

		if (devContext->PoFxPowerSettingCallbackHandle1 != NULL)
		{
			cleanupStatus = PoUnregisterPowerSettingCallback(
				devContext->PoFxPowerSettingCallbackHandle1);
			if (!NT_SUCCESS(cleanupStatus))
			{
				Trace(
					TRACE_LEVEL_ERROR,
					TRACE_INIT,
					"Cleanup failed unregistering AC/DC callback - 0x%08lX",
					cleanupStatus);
			}
			devContext->PoFxPowerSettingCallbackHandle1 = NULL;
		}

		TchFlushDisplayStateWorker(devContext, "OnPrepareHardwareCleanup");
		cleanupStatus = TchDisableDisplayStateHardwareWork(
			devContext,
			"OnPrepareHardwareCleanup");
		if (!NT_SUCCESS(cleanupStatus))
		{
			Trace(
				TRACE_LEVEL_ERROR,
				TRACE_INIT,
				"Cleanup failed disabling display hardware work - 0x%08lX",
				cleanupStatus);
		}

		if (deviceStarted)
		{
			cleanupStatus = TchStopDevice(
				devContext->TouchContext,
				&devContext->I2CContext);
			if (!NT_SUCCESS(cleanupStatus))
			{
				Trace(
					TRACE_LEVEL_ERROR,
					TRACE_INIT,
					"Cleanup failed stopping touch device - 0x%08lX",
					cleanupStatus);
			}
		}

		if (contextAllocated)
		{
			cleanupStatus = TchFreeContext(devContext->TouchContext);
			if (!NT_SUCCESS(cleanupStatus))
			{
				Trace(
					TRACE_LEVEL_ERROR,
					TRACE_INIT,
					"Cleanup failed freeing touch context - 0x%08lX",
					cleanupStatus);
			}
			devContext->TouchContext = NULL;
		}

		if (powerInitialized)
		{
			cleanupStatus = PowerDeInitialize(FxDevice);
			if (!NT_SUCCESS(cleanupStatus))
			{
				Trace(
					TRACE_LEVEL_ERROR,
					TRACE_INIT,
					"Cleanup failed deinitializing touch power - 0x%08lX",
					cleanupStatus);
			}
		}

		if (spbInitialized)
		{
			SpbTargetDeinitialize(FxDevice, &devContext->I2CContext);
		}

		if (devContext->ResetGpio != NULL)
		{
			WdfObjectDelete(devContext->ResetGpio);
			devContext->ResetGpio = NULL;
		}
		devContext->HasResetGpio = FALSE;
		TchSetRuntimeState(devContext, TouchRuntimeFailed, "OnPrepareHardware");
	}

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_INIT,
		"OnPrepareHardware - Exit - 0x%08lX",
		status);
	return status;
}

NTSTATUS
OnReleaseHardware(
	IN WDFDEVICE FxDevice,
	IN WDFCMRESLIST FxResourcesTranslated
)
/*++

  Routine Description:

	This routine cleans up any resources provided.

  Arguments:

	FxDevice - a handle to the framework device object
	FxResourcesRaw - list of translated hardware resources that
		the PnP manager has assigned to the device
	FxResourcesTranslated - list of raw hardware resources that
		the PnP manager has assigned to the device

  Return Value:

	NTSTATUS indicating sucesss or failure

--*/
{
	NTSTATUS status;
	PDEVICE_EXTENSION devContext;

	UNREFERENCED_PARAMETER(FxResourcesTranslated);

	devContext = GetDeviceContext(FxDevice);

	status = STATUS_SUCCESS;
	status = TchStopDisplayStateHardwareWork(devContext, "OnReleaseHardware");
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error stopping display hardware work - 0x%08lX",
			status);
	}

	if (devContext->PoFxPowerSettingCallbackHandle1 != NULL)
	{
		status = PoUnregisterPowerSettingCallback(
			devContext->PoFxPowerSettingCallbackHandle1
		);

		if (!NT_SUCCESS(status))
		{
			Trace(
				TRACE_LEVEL_ERROR,
				TRACE_INIT,
				"Error unregistering power setting callback - 0x%08lX",
				status);
		}
		devContext->PoFxPowerSettingCallbackHandle1 = NULL;
	}

	if (devContext->PoFxPowerSettingCallbackHandle2 != NULL)
	{
		status = PoUnregisterPowerSettingCallback(
			devContext->PoFxPowerSettingCallbackHandle2
		);

		if (!NT_SUCCESS(status))
		{
			Trace(
				TRACE_LEVEL_ERROR,
				TRACE_INIT,
				"Error unregistering power setting callback - 0x%08lX",
				status);
		}
		devContext->PoFxPowerSettingCallbackHandle2 = NULL;
	}

	TchFlushDisplayStateWorker(devContext, "OnReleaseHardware");
	status = TchDisableDisplayStateHardwareWork(devContext, "OnReleaseHardware");
	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error disabling display hardware work - 0x%08lX",
			status);
	}

	TchCompleteIdleIrpWithStatus(
		devContext,
		STATUS_DELETE_PENDING,
		"OnReleaseHardware");

	status = TchStopDevice(devContext->TouchContext, &devContext->I2CContext);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_PNP,
			"Error stopping device - 0x%08lX",
			status);   
	}

	status = TchFreeContext(devContext->TouchContext);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_PNP,
			"Error freeing touch context - 0x%08lX",
			status);   
	}
	else
	{
		devContext->TouchContext = NULL;
	}

	//EventUnregisterMicrosoft_WindowsPhone_TouchMiniDriver();

	//
	// DeInitialize Touch Power
	//
	status = PowerDeInitialize(FxDevice);

	if (!NT_SUCCESS(status))
	{
		Trace(
			TRACE_LEVEL_ERROR,
			TRACE_INIT,
			"Error in touch power deinitialization - 0x%08lX",
			status);
	}

	SpbTargetDeinitialize(FxDevice, &GetDeviceContext(FxDevice)->I2CContext);
	if (devContext->ResetGpio != NULL)
	{
		WdfObjectDelete(devContext->ResetGpio);
		devContext->ResetGpio = NULL;
	}
	devContext->HasResetGpio = FALSE;
	TchSetRuntimeState(devContext, TouchRuntimeUninitialized, "OnReleaseHardware");

	Trace(
		TRACE_LEVEL_INFORMATION,
		TRACE_INIT,
		"OnReleaseHardware - Exit - 0x%08lX",
		status);

	return status;
}

